name: BoxedArp
options:
  bundleIdPrefix: com.opticbox
  deploymentTarget:
    macOS: "12.0"
settings:
  base:
    SWIFT_VERSION: "5.0"
    MACOSX_DEPLOYMENT_TARGET: "12.0"
    CLANG_CXX_LANGUAGE_STANDARD: "c++17"
targets:
  BoxedArp:
    type: application
    platform: macOS
    sources:
      - App
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.opticbox.boxedarp
        PRODUCT_NAME: "BOXED ARP"
        INFOPLIST_FILE: App/Info.plist
        GENERATE_INFOPLIST_FILE: NO
        CODE_SIGNING_ALLOWED: NO
    dependencies:
      - target: BoxedArpAU
        embed: true
  BoxedArpAU:
    type: app-extension
    platform: macOS
    sources:
      - path: BoxedArpAU/AudioUnit
      - path: BoxedArpAU/DSP
      - path: BoxedArpAU/UI
      - path: BoxedArpAU/Config/BoxedArp-Bridging-Header.h
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.opticbox.boxedarp.au
        PRODUCT_NAME: BoxedArpAU
        PRODUCT_MODULE_NAME: BoxedArpAU
        INFOPLIST_FILE: BoxedArpAU/Info.plist
        GENERATE_INFOPLIST_FILE: NO
        SWIFT_OBJC_BRIDGING_HEADER: BoxedArpAU/Config/BoxedArp-Bridging-Header.h
        HEADER_SEARCH_PATHS: "$(SRCROOT)/BoxedArpAU/DSP"
        CODE_SIGN_ENTITLEMENTS: BoxedArpAU/BoxedArpAU.entitlements
        APPLICATION_EXTENSION_API_ONLY: YES
        CODE_SIGNING_ALLOWED: NO
    dependencies:
      - sdk: AudioToolbox.framework
      - sdk: AVFoundation.framework
      - sdk: CoreAudioKit.framework
      - sdk: Cocoa.framework
schemes:
  BoxedArp:
    build:
      targets:
        BoxedArp: all
        BoxedArpAU: all
    run:
      config: Debug
    archive:
      config: Release
